WebApiGatewaySettings:
    Secret: THIS_IS_A_RANDOM_SECRET_2e7a1e80-16ee-4e52-b5c6-5e8892453459
    AllowedChatOrigins:
        - https://localhost:44300
        - https://localhost:44398
Routes:
#
#   ServiceName: Microservices.Demo.Auth.API
#
    -    
        DownstreamPathTemplate: /api/Users
        DownstreamScheme: http
        UpstreamPathTemplate: /api/Users
        ServiceName: Microservices.Demo.Auth.API
        UpstreamHttpMethod: 
            - Get
        FileCacheOptions: 
            TtlSeconds: 15
        AuthenticationOptions:
            AuthenticationProviderKey: ApiSecurityAuthenticationScheme
        RouteClaimsRequirement:
            userType: SALESMAN      
        DangerousAcceptAnyServerCertificateValidator: true
#
#   ServiceName: Microservices.Demo.Auth.API
#
    -
        DownstreamPathTemplate: /api/Users
        DownstreamScheme: http
        UpstreamPathTemplate: /api/Users
        ServiceName: Microservices.Demo.Auth.API
        UpstreamHttpMethod:
            - Post
        FileCacheOptions: 
            TtlSeconds: 15        
        DangerousAcceptAnyServerCertificateValidator: true
#
#   ServiceName: Microservices.Demo.Product.API
#
    -    
        DownstreamPathTemplate: /api/Products/{everything}
        DownstreamScheme: http
        UpstreamPathTemplate: /api/Products/{everything}
        ServiceName: Microservices.Demo.Product.API
        UpstreamHttpMethod: 
            - Get
        FileCacheOptions: 
            TtlSeconds: 15
        AuthenticationOptions:
            AuthenticationProviderKey: ApiSecurityAuthenticationScheme
        RouteClaimsRequirement:
            userType: SALESMAN      
        DangerousAcceptAnyServerCertificateValidator: true
#
#   ServiceName: Microservices.Demo.Product.API
#
    -
        DownstreamPathTemplate: /api/Products
        DownstreamScheme: http
        UpstreamPathTemplate: /api/Products
        ServiceName: Microservices.Demo.Product.API
        UpstreamHttpMethod:
            - Get
        FileCacheOptions: 
            TtlSeconds: 15
        AuthenticationOptions:
            AuthenticationProviderKey: ApiSecurityAuthenticationScheme
        RouteClaimsRequirement:
            userType: SALESMAN      
        DangerousAcceptAnyServerCertificateValidator: true
#
#   ServiceName: Microservices.Demo.Policy.API
#
    -
        DownstreamPathTemplate: /api/Offers
        DownstreamScheme: http
        UpstreamPathTemplate: /api/Offers
        ServiceName: Microservices.Demo.Policy.API
        UpstreamHttpMethod: 
            - Post
        AuthenticationOptions:
            AuthenticationProviderKey: ApiSecurityAuthenticationScheme
        RouteClaimsRequirement:
            userType: SALESMAN      
        DangerousAcceptAnyServerCertificateValidator: true
        AddHeadersToRequest:
            AgentLogin: Claims[http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier] > value[0] > |
#
#   ServiceName: Microservices.Demo.Policy.API
#
    -
        DownstreamPathTemplate: /api/Policies
        DownstreamScheme: http
        UpstreamPathTemplate: /api/Policies
        ServiceName: Microservices.Demo.Policy.API
        UpstreamHttpMethod: 
            - Post
        AuthenticationOptions:
            AuthenticationProviderKey: ApiSecurityAuthenticationScheme
        RouteClaimsRequirement:
            userType: SALESMAN
        DangerousAcceptAnyServerCertificateValidator: true
#
#   ServiceName: Microservices.Demo.Policy.API
#
    -
        DownstreamPathTemplate: /api/Policies/{number}
        DownstreamScheme: http
        UpstreamPathTemplate: /api/Policies/{number}
        ServiceName: Microservices.Demo.Policy.API
        UpstreamHttpMethod: 
            - Get
        FileCacheOptions: 
            TtlSeconds: 15
        AuthenticationOptions:
            AuthenticationProviderKey: ApiSecurityAuthenticationScheme
        RouteClaimsRequirement:
            userType: SALESMAN      
        DangerousAcceptAnyServerCertificateValidator: true
#
#   ServiceName: Microservices.Demo.PolicySearch.API
#
    -
        DownstreamPathTemplate: /api/PoliciesSearch
        DownstreamScheme: http
        UpstreamPathTemplate: /api/PoliciesSearch
        ServiceName: Microservices.Demo.PolicySearch.API
        UpstreamHttpMethod: 
            - Get
        AuthenticationOptions:
            AuthenticationProviderKey: ApiSecurityAuthenticationScheme
        RouteClaimsRequirement: 
            userType: SALESMAN
        DangerousAcceptAnyServerCertificateValidator: true
#   RATG CAMBIOS
#   ServiceName: Microservices.Demo.Report.API
#
    -
        DownstreamPathTemplate: /api/Report/ReportPolicy
        DownstreamScheme: http
        UpstreamPathTemplate: /api/Report/ReportPolicy
        ServiceName: Microservices.Demo.Report.API
        UpstreamHttpMethod: 
            - Get
        FileCacheOptions: 
            TtlSeconds: 15
        AuthenticationOptions:
            AuthenticationProviderKey: ApiSecurityAuthenticationScheme
        RouteClaimsRequirement:
            userType: SALESMAN
        DangerousAcceptAnyServerCertificateValidator: true
GlobalConfiguration:
    RequestIdKey: OcRequestId
    AdministrationPath: /administration
    UseServiceDiscovery: true
    ServiceDiscoveryProvider:
        Type: Eureka
        Host: microservices.demo.discoveryserver
        Port: 8761